def path_in_cell(*args, **kwargs): ...
def geometric_factors(*args, **kwargs): ...
def cell_interpolator(*args, **kwargs): ...
def linthrd2cart(*args, **kwargs): ...
def cart2linthrd(*args, **kwargs): ...
