include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build

.common:
  extends: .uenv-runner-daint-gh200
  stage: build
  variables:
    WITH_UENV_VIEW: default
  script:
    - python -m venv env
    - source env/bin/activate
    - MPICC=mpicc python -m pip install --no-binary=mpi4py --no-cache-dir mpi4py .[test]
    - pytest
    - deactivate

build prgenv 25.6:
  extends: .common
  image: prgenv-gnu/25.6:v2

build prgenv 25.11:
  extends: .common
  image: prgenv-gnu/25.11:v1

build prgenv 26.3:
  extends: .common
  image: prgenv-gnu/26.3:v1
